# version: "3.9"

# services:
#   web_users:
#     container_name: users-service
#     build: ./
#     restart: always
#     expose:
#       - 8000
#     env_file:
#       - .env
#     depends_on:
#       db:
#         condition: service_healthy
  db:
    container_name: users-service-db
    image: postgres:14-alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
