# Generated by Django 4.2.8 on 2023-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "usd"), ("EUR", "eur"), ("GBP", "gbp")],
                default="usd",
                max_length=3,
            ),
        ),
    ]
